# Generated by Django 5.2.15 on 2026-06-22 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AuthApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloth_type', models.CharField(choices=[('Trouser', 'Trouser'), ('Barmuda', 'Barmuda'), ('Paijama', 'Paijama'), ('Skirt', 'Skirt'), ('Leggings', 'Leggings'), ('Shirt', 'Shirt'), ('Kurta', 'Kurta'), ('Kurti', 'Kurti'), ('Shrewani', 'Shrewani'), ('Coat', 'Coat'), ('Jacket', 'Jacket'), ('Blouse', 'Blouse'), ('Gown', 'Gown'), ('Frock', 'Frock')], default=' ', max_length=20, unique=True)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeOfCloth', models.CharField(choices=[('Trouser', 'Trouser'), ('Barmuda', 'Barmuda'), ('Paijama', 'Paijama'), ('Skirt', 'Skirt'), ('Leggings', 'Leggings'), ('Shirt', 'Shirt'), ('Kurta', 'Kurta'), ('Kurti', 'Kurti'), ('Shrewani', 'Shrewani'), ('Coat', 'Coat'), ('Jacket', 'Jacket'), ('Blouse', 'Blouse'), ('Gown', 'Gown'), ('Frock', 'Frock')], default=' ', max_length=30)),
                ('material', models.CharField(choices=[('cotton', 'cotton'), ('silk', 'silk'), ('wool', 'wool')], default=' ', max_length=30)),
                ('image', models.ImageField(upload_to='uploads/None')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AuthApp.customer')),
            ],
        ),
        migrations.CreateModel(
            name='LowerBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.IntegerField(default=0)),
                ('hips', models.IntegerField(default=0)),
                ('thigh', models.IntegerField(default=0)),
                ('knee', models.IntegerField(default=0)),
                ('ankle', models.IntegerField(default=0)),
                ('pantBottom', models.IntegerField(default=0)),
                ('uCrouch', models.IntegerField(default=0)),
                ('clothType', models.CharField(choices=[(' ', ' '), ('Trouser', 'Trouser'), ('Barmuda', 'Barmuda'), ('Paijama', 'Paijama'), ('Skirt', 'Skirt'), ('Leggings', 'Leggings')], default=' ', max_length=20)),
                ('requirements', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Cloth.options')),
            ],
        ),
        migrations.CreateModel(
            name='UpperBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.IntegerField(default=0)),
                ('chest', models.IntegerField(default=0)),
                ('upperChest', models.IntegerField(default=0)),
                ('waist', models.IntegerField(default=0)),
                ('hips', models.IntegerField(default=0)),
                ('shoulder', models.IntegerField(default=0)),
                ('sleeves', models.IntegerField(default=0)),
                ('biceps', models.IntegerField(default=0)),
                ('armHold', models.IntegerField(default=0)),
                ('elbow', models.IntegerField(default=0)),
                ('collar', models.IntegerField(default=0)),
                ('backLength', models.IntegerField(default=0)),
                ('crossBack', models.IntegerField(default=0)),
                ('bustLength', models.IntegerField(default=0)),
                ('apexGap', models.IntegerField(default=0)),
                ('bottomWidth', models.IntegerField(default=0)),
                ('clothType', models.CharField(choices=[(' ', ' '), ('Shirt', 'Shirt'), ('Kurta', 'Kurta'), ('Kurti', 'Kurti'), ('Shrewani', 'Shrewani'), ('Coat', 'Coat'), ('Jacket', 'Jacket'), ('Blouse', 'Blouse'), ('Gown', 'Gown'), ('Frock', 'Frock')], default=' ', max_length=20)),
                ('pocket', models.BooleanField(default=False)),
                ('button', models.CharField(choices=[('Normal', 'Normal'), ('Snap', 'Snap'), ('Flat Shank', 'Flat Shank'), ('Hook', 'Hook')], default='Normal', max_length=20)),
                ('sleeveType', models.CharField(choices=[('Full', 'Full'), ('Half', 'Half'), ('No Sleeve', 'No Sleeve')], default='Full', max_length=20)),
                ('requirments', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Cloth.options')),
            ],
        ),
    ]
