# Generated by Django 5.2.15 on 2026-06-23 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cloth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lowerbody',
            name='requirements',
        ),
        migrations.RemoveField(
            model_name='upperbody',
            name='requirments',
        ),
        migrations.AddField(
            model_name='lowerbody',
            name='requirements',
            field=models.ManyToManyField(blank=True, null=True, to='Cloth.options'),
        ),
        migrations.AddField(
            model_name='upperbody',
            name='requirments',
            field=models.ManyToManyField(blank=True, null=True, to='Cloth.options'),
        ),
    ]
