# Generated by Django 5.2.15 on 2026-06-23 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cloth', '0002_remove_lowerbody_requirements_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lowerbody',
            name='requirements',
        ),
        migrations.RemoveField(
            model_name='upperbody',
            name='requirments',
        ),
        migrations.AddField(
            model_name='lowerbody',
            name='requirements',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Cloth.options'),
        ),
        migrations.AddField(
            model_name='upperbody',
            name='requirments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Cloth.options'),
        ),
    ]
