# Generated by Django 5.2.15 on 2026-06-27 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cloth', '0003_remove_lowerbody_requirements_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upperbody',
            old_name='requirments',
            new_name='requirements',
        ),
        migrations.AlterField(
            model_name='lowerbody',
            name='clothType',
            field=models.CharField(choices=[('Trouser', 'Trouser'), ('Barmuda', 'Barmuda'), ('Paijama', 'Paijama'), ('Skirt', 'Skirt'), ('Leggings', 'Leggings')], default=' ', max_length=20),
        ),
        migrations.AlterField(
            model_name='upperbody',
            name='clothType',
            field=models.CharField(choices=[('Shirt', 'Shirt'), ('Kurta', 'Kurta'), ('Kurti', 'Kurti'), ('Shrewani', 'Shrewani'), ('Coat', 'Coat'), ('Jacket', 'Jacket'), ('Blouse', 'Blouse'), ('Gown', 'Gown'), ('Frock', 'Frock')], default=' ', max_length=20),
        ),
    ]
