# Generated by Django 5.2.15 on 2026-06-27 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cloth', '0004_rename_requirments_upperbody_requirements_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lowerbody',
            name='requirements',
        ),
        migrations.RemoveField(
            model_name='upperbody',
            name='requirements',
        ),
        migrations.AddField(
            model_name='options',
            name='lower_body',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='Cloth.lowerbody'),
        ),
        migrations.AddField(
            model_name='options',
            name='upper_body',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='Cloth.upperbody'),
        ),
    ]
