# Generated by Django 5.2.15 on 2026-07-12 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cloth', '0005_remove_lowerbody_requirements_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lowerbody',
            name='waist',
            field=models.IntegerField(default=0),
        ),
    ]
