# Generated by Django 5.2.15 on 2026-06-22 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AuthApp', '0001_initial'),
        ('Cloth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Confirmed', 'Confirmed'), ('Processing', 'Processing'), ('Urgent', 'Urgent'), ('Complated', 'Complated'), ('Delivered', 'Delivered'), ('Cenceled', 'Cenceled')], default='New', max_length=20)),
                ('in_time', models.DateTimeField(auto_now_add=True)),
                ('days', models.PositiveIntegerField(default=7, help_text='Days to complete the order')),
                ('out_time', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AuthApp.customer')),
                ('lowerBody', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Cloth.lowerbody')),
                ('upperBody', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Cloth.upperbody')),
            ],
        ),
    ]
