# Generated by Django 5.2.15 on 2026-06-23 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cloth', '0002_remove_lowerbody_requirements_and_more'),
        ('Order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='lowerBody',
        ),
        migrations.RemoveField(
            model_name='order',
            name='upperBody',
        ),
        migrations.AddField(
            model_name='order',
            name='lowerBody',
            field=models.ManyToManyField(blank=True, null=True, to='Cloth.lowerbody'),
        ),
        migrations.AddField(
            model_name='order',
            name='upperBody',
            field=models.ManyToManyField(blank=True, null=True, to='Cloth.upperbody'),
        ),
    ]
