# Generated by Django 5.2.15 on 2026-06-23 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cloth', '0003_remove_lowerbody_requirements_and_more'),
        ('Order', '0002_remove_order_lowerbody_remove_order_upperbody_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='lowerBody',
        ),
        migrations.RemoveField(
            model_name='order',
            name='upperBody',
        ),
        migrations.AddField(
            model_name='order',
            name='lowerBody',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Cloth.lowerbody'),
        ),
        migrations.AddField(
            model_name='order',
            name='upperBody',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Cloth.upperbody'),
        ),
    ]
