# Generated by Django 5.2.15 on 2026-07-11 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cloth', '0005_remove_lowerbody_requirements_and_more'),
        ('Order', '0003_remove_order_lowerbody_remove_order_upperbody_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='lowerBody',
        ),
        migrations.RemoveField(
            model_name='order',
            name='upperBody',
        ),
        migrations.CreateModel(
            name='OrderBottomItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('lower_body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cloth.lowerbody')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bottoms', to='Order.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderTopItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tops', to='Order.order')),
                ('upper_body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cloth.upperbody')),
            ],
        ),
    ]
