# Generated by Django 5.2.15 on 2026-07-12 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0004_remove_order_lowerbody_remove_order_upperbody_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderbottomitem',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='ordertopitem',
            name='quantity',
        ),
    ]
