# Generated by Django 5.2.15 on 2026-07-12 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0005_remove_orderbottomitem_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='urgent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Confirmed', 'Confirmed'), ('Processing', 'Processing'), ('Complated', 'Complated'), ('Delivered', 'Delivered'), ('Cenceled', 'Cenceled')], default='Confirmed', max_length=20),
        ),
    ]
