# Generated by Django 5.2.15 on 2026-07-11 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Order', '0004_remove_order_lowerbody_remove_order_upperbody_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='recipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_at', models.DateField(auto_now_add=True)),
                ('totalAmount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('paidAmout', models.DecimalField(decimal_places=2, max_digits=5)),
                ('paymentStatus', models.CharField(choices=[('Balance', 'Balance'), ('Paid', 'Paid')], default='Balance', max_length=20)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Order.order')),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloth', models.CharField(max_length=10)),
                ('quantity', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('recipt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bill.recipt')),
            ],
        ),
    ]
